# Generated by Django 4.2.2 on 2023-07-12 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_alter_product_datetime_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=1, verbose_name="I's Active"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 12, 59, 17, 303065, tzinfo=datetime.timezone.utc), verbose_name='Date Time Created'),
        ),
        migrations.AddField(
            model_name='category',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Time Updated'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 12, 59, 17, 303627, tzinfo=datetime.timezone.utc), verbose_name='Date Time Created'),
        ),
    ]
