# Generated by Django 4.2.2 on 2023-07-15 10:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_product_category_alter_category_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 10, 53, 27, 263244, tzinfo=datetime.timezone.utc), verbose_name='Date Time Created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 10, 53, 27, 263871, tzinfo=datetime.timezone.utc), verbose_name='Date Time Created'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('active', models.BooleanField(default=True, verbose_name='Its Active')),
                ('datetime_create', models.DateTimeField(default=datetime.datetime(2023, 7, 15, 10, 53, 27, 265093, tzinfo=datetime.timezone.utc), verbose_name='Time created')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='product.comment', verbose_name='Reply comment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.product', verbose_name='Product')),
                ('user', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
