# Generated by Django 4.2.2 on 2023-07-18 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_datetime_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='Product/img', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=1, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 7, 34, 47, 720798, tzinfo=datetime.timezone.utc), verbose_name='Date Time Created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 7, 34, 47, 722896, tzinfo=datetime.timezone.utc), verbose_name='Time created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 7, 34, 47, 721465, tzinfo=datetime.timezone.utc), verbose_name='Date Time Created'),
        ),
    ]
