# Generated by Django 4.2.2 on 2023-07-18 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_category_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 7, 44, 37, 620672, tzinfo=datetime.timezone.utc), verbose_name='Date Time Created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 7, 44, 37, 623129, tzinfo=datetime.timezone.utc), verbose_name='Time created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 7, 44, 37, 621407, tzinfo=datetime.timezone.utc), verbose_name='Date Time Created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='Image/Products', verbose_name='Image'),
        ),
    ]
