# Generated by Django 4.2.2 on 2023-07-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_category_datetime_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='datetime_create',
        ),
        migrations.AlterField(
            model_name='category',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Time Created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Time Created'),
        ),
    ]
