# Generated by Django 4.2.2 on 2023-07-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_comment_datetime_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='datetime_created_comment',
            field=models.DateTimeField(auto_now=True, verbose_name='Time created'),
        ),
    ]
