# Generated by Django 4.2.2 on 2023-07-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_comment_datetime_created_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime_created_comment',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time created'),
        ),
    ]
